services:
  traefik-log-processor:
    build: .
    container_name: traefik-log-processor
    volumes:
      # Mount Traefik logs directory
      - /path/to/traefik/logs:/logs:ro

      # Mount output directory for split logs
      - /path/to/output:/output

      # Mount custom configuration (optional)
      - ./config.yaml:/app/config.yaml:ro

    # For better container management
    restart: unless-stopped

    # Resource limits to keep it lightweight
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
